### ISSUE TITLE
Doesn

### ISSUE THREAD

**Issue by nahilaChowdhury** [nahilaChowdhury/shiny-octo-succotash#10]

**Comment by nahilaChowdhury** [comment]
@WK-GiHu

Program doesn't get self.a_star.get()

AttributeError: 'Analysis_Page' object has no attribute 'a_star'

https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/1d007fda9da76dce2de5772582284296ffb16f02/mark_analysis_18-%20gui.py#L763

**Comment by WK-GiHu** [comment]
@nahilaChowdhury 

>AttributeError: 'Analysis_Page' object has no attribute 'a_star'

You have defined
https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/1d007fda9da76dce2de5772582284296ffb16f02/mark_analysis_18-%20gui.py#L727

Show the full Traceback

**Comment by nahilaChowdhury** [comment]
@WK-GiHu

I have identified the error, i did command = self.enter_grade() indstead of self.enter_grade
