### ISSUE TITLE
Why is Button parameter “command” executed when declared?

### ISSUE THREAD

**Issue by WK-GiHu** [nahilaChowdhury/shiny-octo-succotash#12]
@nahilaChowdhury 

The following statement is wrong:
https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/3af90b6e0088963de18a9cd9f3454ebdbdcdce17/Mark%20Analysis%202#L784

Read [Why is Button parameter “command” executed when declared?](https://stackoverflow.com/questions/5767228/why-is-button-parameter-command-executed-when-declared)

**Comment by nahilaChowdhury** [comment]
@WK-GiHu 

I've changed the line to: https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/dfaf5a77f8016b12d7ab6191438004df4d73093f/Mark%20Analysis%202#L784

It gives me no errors, however, it doesn't fully go through the validation process before changing frames.

**Comment by WK-GiHu** [comment]
@nahilaChowdhury 

>it doesn't fully go through the validation process before changing frames.

1. I couldn't imagin this will work?
  At `lambda` execution, both functions, `.percentage()` and `.show_frame(...` are executed at once.

2. You are using the wrong variable here:
  https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/dfaf5a77f8016b12d7ab6191438004df4d73093f/Mark%20Analysis%202#L962-L964
  I rephrase it, to make it clear, but this will not work either as you need the argument from the second function `(Analysis_Page)`.
    ```
    for func in args:
    ```

---

I recommend to use a function closure, e.g:
https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/dfaf5a77f8016b12d7ab6191438004df4d73093f/Mark%20Analysis%202#L768
```
    def __init__(self, parent, controller):
        ...
        def on_enter_button():
            self.percentage()
            controller.show_frame(Analysis_Page)

        enter_button = tk.Button(self, text="Enter", command=on_enter_button)
        ...
```

**Comment by nahilaChowdhury** [comment]
@WK-GiHu 
still the same problem :/ I can't imagine why tho? What if I made a separate function that validates the total mark?

update: no it doesn't work

**Comment by nahilaChowdhury** [comment]
@WK-GiHu 
if i do:
def on_enter_button():
            print("Does on enter button function work?")
            if self.validate_total_mark() ==True:
                self.percentage()
                controller.show_frame(Analysis_Page)

the total_mark validates. But the other functions no longer run

**Comment by WK-GiHu** [comment]
@nahilaChowdhury 

>But the other functions no longer run

It's not clear what you mean with **other functions**.
I mean:
- [ ] `self.percentage()`
- [ ] `controller.show_frame(Analysis_Page)`

It's not clear what you mean with: **no longer run**?

**Comment by nahilaChowdhury** [comment]
This is what I have tried:

I have added the percentage function at the end of def validate_total_mark:
https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/bb6713d7c76ea24fb5a0c7284bad8f2943fd082f/Mark%20Analysis%202#L930

This works to validate the total mark and carry out def percentage().
However, I cannot figure out how to switch frames after that.

**Comment by nahilaChowdhury** [comment]
@WK-GiHu 
Mistake in https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/bb6713d7c76ea24fb5a0c7284bad8f2943fd082f/Mark%20Analysis%202#L932

should be lambda:controller.show_frame(Analysis_page)

seems to have worked.

**Comment by nahilaChowdhury** [comment]
update: solved.

https://github.com/nahilaChowdhury/shiny-octo-succotash/blob/ef312379a8494b42fc7bb010dae7defaf15f57ce/Mark%20Analysis%202#L770
